Eliminados code smells de views - Refactorizado de código
eventshow/eventshow pull request #129
Opened 2020-04-23 17:16 UTC by angbongon

2020-04-24 14:19 UTC, angbongon commented
Funcionalidades a revisar:
- Actualizar evento
- Puntuar asistente

2020-04-24 23:49 UTC, angelcalzadollamas requested changes
Da igual con que puntuación puntue a un asistente, que siempre se me muestra en la lista de attendees que le he puntuado con 5 estrellas. Imagen:

![Captura](https://user-images.githubusercontent.com/28622424/80265162-e4333900-8696-11ea-9474-8519485cb11f.PNG)

2020-04-24 23:51 UTC, angcallla commented
No espera es otra cosa lo que ocurre, lo hablamos mañana mejor. Creo que es de front end el problema

2020-04-25 10:07 UTC, angelcalzadollamas approved these changes
Como has hecho otra pull para el problema que te comenté, con respecto a esto todo correcto. Avisaré a juanmi en el daily de este problema para que lo tenga en cuenta si hay otros tags

2020-04-25 12:14 UTC, merged