CU-10 Gestionar eventos
eventshow/eventshow pull request #29
Opened 2020-03-25 21:17 UTC by raunavcru

Se ha corregido:
-La capacidad ya no puede ser cero
-Ya no peta al pone un string en las fechas
-Ya no existe la categoria por defecto '-----------'
-Ya no se puede crear eventos con fechas pasadas

2020-03-25 21:35 UTC, angbongon submitted a review, later dismissed
Todo correcto, se espera a que lo revisen en QA

2020-03-26 10:38 UTC, angcallla commented
Comprobaciones (en **x** las que están correctas):

- [x]  Crea evento normal
- [x]  Formulario en blanco
- [x]  select dato erróneo
- [x]  fecha pasada
- [x]  aforo igual a 0
- [x]  <script> en los strings
- [x]  hora sin patrón
- [ ]  fecha sin patrón

Cuando introduzco en el input fecha: "eeee" da el mismo error que daba con la hora mal

2020-03-26 10:58 UTC, angelcalzadollamas requested changes
Cambios comentados en el anterior comentario

2020-03-26 11:24 UTC, angelcalzadollamas approved these changes

2020-03-26 11:28 UTC, angelcalzadollamas requested changes
_Editar_
- Impedir que se edite un evento ya pasado

_Borrar_
- Impedir que se borre un evento ya pasado

2020-03-26 12:33 UTC, angelcalzadollamas approved these changes

2020-03-26 12:33 UTC, merged