CU-07 Ver registro de pagos
eventshow/eventshow pull request #44
Opened 2020-03-27 17:27 UTC by raunavcru

2020-03-27 20:42 UTC, angbongon requested changes
Parece que hay un error en las urls y hace que la build de Travis falle, corrígelo.

2020-03-27 20:42 UTC, angbongon commented on events/urls.py
> +    path('my_transaction', views.TransactionListView.as_view(), name='my_transaction')
Aquí falta una coma

2020-03-28 11:08 UTC, angbongon requested changes
Quita el code smell que hay

2020-03-28 11:16 UTC, angbongon submitted a review, later dismissed
Se aceptan los cambios

2020-03-28 20:06 UTC, angelcalzadollamas reviewed
Me meto en el enlace: http://127.0.0.1:8000/my_transaction y no se ve nada. No sé exactamente qué debo revisar, además todavía no está stripe implementado del todo

2020-03-28 20:27 UTC, angelcalzadollamas submitted a review, later dismissed
Correcto por parte del back, a la espera de la vista

2020-03-28 20:45 UTC, angbongon approved these changes
Se aceptan los cambios

2020-03-28 20:45 UTC, merged