CU-24 Avisar de rellenar campos para crear evento
eventshow/eventshow pull request #46
Opened 2020-03-27 19:06 UTC by rojas1995

Ahora te avisa de que tienes que tener rellenos los campos de nombre, apellidos y bio antes de poder hacer un evento

2020-03-27 20:40 UTC, angbongon requested changes
Con los cambios que he pedido sería suficiente para pasarlo a QA.

2020-03-27 20:40 UTC, angbongon commented on events/views.py
> +            context['first_name'] = self.request.user.first_name == '' or self.request.user.first_name == None
En Python los strings vacíos son None, así que puedes hacer las comprobaciones directamente con: `not profile.bio`. Por ejemplo.

2020-03-28 15:25 UTC, angbongon submitted a review, later dismissed
Se aceptan los cambios y se pasa a QA

2020-03-28 16:16 UTC, angbongon commented
@angcallla cuando aceptes los cambios avísame y hago yo el merge

2020-03-29 00:34 UTC, angelcalzadollamas requested changes
Me he registrado, he modificado **Solo** mi **bio** y ya me ha dejado entrar a crear un evento.

Comprueba de nuevo que hasta que no estén los 3 datos no se pueda.

2020-03-29 15:33 UTC, merged