CU-20 Notificación evento cancelado / CU-22 Notificación evento modificado
eventshow/eventshow pull request #47
Opened 2020-03-27 20:15 UTC by raunavcru

2020-03-27 20:36 UTC, angbongon requested changes
Cambia lo que te he dicho y pido la review de QA

2020-03-27 20:36 UTC, angbongon commented on events/views.py
> +            event = models.Event.objects.get(pk=event_pk)
Si puedes saca todo esto a una función en los servicios que reciba como parámetro el evento, el asunto y cuerpo del mensaje. Para evitar duplicado de código y tener una funcionalidad reutilizable

2020-03-28 11:11 UTC, angbongon submitted a review, later dismissed
Todo en orden

2020-03-28 12:29 UTC, angelcalzadollamas submitted a review, later dismissed
Me sale el error comentado en slack, hay que arreglarlo

2020-03-28 17:02 UTC, angbongon commented on events/services.py
> +class EmailService:
Lo mejor sería que recibiera recipients como argumento, así es reutilizable en todos lados.

2020-03-28 17:14 UTC, raunavcru commented
Antes se le pasaba el recipient como parámetro y me dijiste que le pasara como parámetro el event_pk.

2020-03-28 17:29 UTC, angbongon commented
Ya hahaha, pero me he dado cuenta ahora que es peor, lo ziento. :|

2020-03-29 15:32 UTC, merged