CU-04 Filter events
eventshow/eventshow pull request #59
Opened 2020-03-29 18:07 UTC by santiborge97

2020-03-29 18:20 UTC, angbongon commented
Corrige los code smells que no son de CSS o HTML

2020-03-30 18:55 UTC, angbongon commented
Muchos de los bugs y code smells pertenecen a templates que ya no se usan, otros son por tema de código comentado que se dejará así para el sprint 3

2020-03-30 19:34 UTC, angelcalzadollamas requested changes
En precio mínimo y precio máximo si pongo: 2. ó .0 falla el pattern

2020-03-30 19:43 UTC, angelcalzadollamas requested changes
Prueba a poner 0. Te fallará

2020-03-30 19:45 UTC, angbongon commented
> Prueba a poner 0. Te fallará

No estoy viendo ese error

2020-03-30 19:58 UTC, angelcalzadollamas approved these changes
Todo correcto, buen trabajo

2020-03-30 19:59 UTC, merged