CU-25 Derecho al olvido
eventshow/eventshow pull request #65
Opened 2020-04-03 17:59 UTC by angbongon

Se ha implementado de forma que se eliminan todos los datos personales del usuario, pero los eventos creados por el mismo se mantienen, al igual que las puntuaciones (en las que es revisor) y las transacciones en las que ha intervenido.

2020-04-04 13:05 UTC, angelcalzadollamas requested changes
Cosas que se deben corregir:

- Si busco un evento del usuario delete que no ha acabado, me puedo inscribir a él (mi consejo: poner los eventos de los usuarios eliminados a pasado)
- Si el usuario delete tiene un enrollment de un evento aceptado y me logeo como el anfitrión de ese evento, puedo ver que un tal "delete" va a asistir a mi evento . (mi consejo, cancelar los enrollments de eventos aún no empezados)

2020-04-04 23:49 UTC, angelcalzadollamas requested changes
Cosas que corregir:

1. Si un usuario A es un asistente aceptado de un evento pasado de un usuario B. Cuando B borra sus datos, A puede puntuar al usuario Delete. Esto es porque al ser el evento pasado, no borramos ni el evento ni sus enrollments por lo que sigue saliendo en la lista de eventos como asistente de A. Posible solución: Eliminar los enrollments a los eventos del usuario delete.

2. Debes eliminar los enrollments que ha hecho deleted a eventos futuros también porque estos cuando acaban, si pongo la id de deleted en la puntuación, lo puedo puntuar.

Resumen: Creo que esto alfinal va a tener brechas en más de un sitio y además es muy complicado de revisar, yo lo dejaría en guardar solo los eventos pasados del usuario y eliminar todos lo demas: Enrollments a esos eventos, ratings al usuario eliminado, enrollments que el eliminado ha hecho, ratings que el eliminado ha hecho, etc.

Te dejo un ejemplo para que veas como soy capaz de puntuar al deleted:
![Puedo puntuar a deleted](https://user-images.githubusercontent.com/28622424/78463653-bc783300-76df-11ea-919a-03163c40d5fb.PNG)

2020-04-05 21:30 UTC, angelcalzadollamas requested changes
Correcciones:

1. Cuando un usuario va a puntuar a los asistentes de un evento y un asistente se eliminó sale en la lista de asistentes como deleted. Te dejo una imagen para que lo veas.

![Huespedes del evento](https://user-images.githubusercontent.com/28622424/78510438-5ea62280-7795-11ea-9a25-68d353c088b8.PNG)


2. Cuando un usuario intenta puntuar al anfitrión delete le sale dos mensajes de que no puede, creo que se solapan. Te dejo una imagen abajo con lo que me refiero. Es la primera fila

![Veo que se solapan estos mensajes de no disponible](https://user-images.githubusercontent.com/28622424/78510422-5221ca00-7795-11ea-9d0c-123ee3e199a5.PNG)

2020-04-05 22:11 UTC, angbongon commented
> Correcciones:
> 
> 1. Cuando un usuario va a puntuar a los asistentes de un evento y un asistente se eliminó sale en la lista de asistentes como deleted. Te dejo una imagen para que lo veas.
> 
> ![Huespedes del evento](https://user-images.githubusercontent.com/28622424/78510438-5ea62280-7795-11ea-9a25-68d353c088b8.PNG)
> 
> 
> 2. Cuando un usuario intenta puntuar al anfitrión delete le sale dos mensajes de que no puede, creo que se solapan. Te dejo una imagen abajo con lo que me refiero. Es la primera fila
> 
> ![Veo que se solapan estos mensajes de no disponible](https://user-images.githubusercontent.com/28622424/78510422-5221ca00-7795-11ea-9d0c-123ee3e199a5.PNG)

La segunda foto es algo relacionado más bien con el front. La primera es porque en principio los enrollments hechos a eventos pasados no se eliminan, si quieres que aparezca otra clase de información es algo referente al front, si quieres que se eliminen todos los enrollments del usuario eliminado lo hago así.

2020-04-05 22:12 UTC, angbongon commented
Yo creo que para el asistente lo mejor es dejar no disponible en todos los campos, pero como prefieras

2020-04-06 11:23 UTC, angbongon commented
La parte de front no la voy a tocar porque tampoco sé cómo lo quieren poner @angcallla

2020-04-06 12:37 UTC, angcallla commented
Vale, me lo he apuntado para que lo hablemos con los front.

2020-04-06 19:04 UTC, angelcalzadollamas submitted a review, later dismissed
Todo correcto, a la espera de arreglar el solapamiento front end cuando se acepten la otra pull request

2020-04-06 21:56 UTC, merged