pdf con los datos de usuario
eventshow/eventshow pull request #66
Opened 2020-04-03 20:17 UTC by rojas1995

Ten en cuenta que actualizo el requeriments con la librería  de pdf

2020-04-04 15:18 UTC, angbongon commented
Resuelve los conflictos, parace que tienes una url mal puesta, seguramente una coma. Al resolver los conflictos debería solucionarse.

2020-04-04 15:46 UTC, rojas1995 commented
Ya lo he solucionado, era una coma lo que faltaba.

2020-04-05 12:13 UTC, angbongon submitted a review, later dismissed
Se aceptan los cambios y se pasa a QA para ver si es necesario añadir más información

2020-04-05 23:21 UTC, angelcalzadollamas requested changes
Con motivo de tenerlo ya preparado, ¿sería complicado añadir también los recibos del usuario? Si se puede hacer ya hagámoslo cuanto antes.

Me he dado cuenta que el botón "descargar datos" en datos personales ahora mismo no lleva a esta funcionalidad. Háblalo con juanmi a ver si lo puedes enlazar ya correctamente.

2020-04-07 00:42 UTC, angelcalzadollamas submitted a review, later dismissed
Todo correcto.

2020-04-07 12:29 UTC, merged