Cu-29 y Cu-30
eventshow/eventshow pull request #69
Opened 2020-04-04 16:42 UTC by raunavcru

Para probarlo el host debe estar logueado en Stripe, entonces cuando os pida las credenciales al intentar cobrar un evento os logueais en el formulario como showman335@gmail.com (la contraseña es la misma que la de nuestro correo) y le dais a omitir formulario y ya le podeis volver a dar a cobrar.

Para comprobar si el pago se ha realizado inica sesion en https://dashboard.stripe.com/login con showman335 que va a ser el host (aunque en la aplicacion no tiene que ser showman el usuario, es para no hacer 17 cuentas) y en una ventana de incógnito como contacteventshow@gmail.com

He cambiado el modelo así que toca volver a migrar el modelo y a repopular

2020-04-04 16:56 UTC, raunavcru commented
Los Code Smells que hay: uno es del migrate y otro es la complejidad ciclomática que no creo que pueda bajarla a 15 porque la view tiene bastantes restricciones

2020-04-04 23:59 UTC, angcallla commented
Espero a que angel acepte para comprobarlo yo

2020-04-05 12:37 UTC, angbongon requested changes
Con esos cambios lo pasamos a QA

2020-04-05 12:37 UTC, angbongon commented on events/models.py
> +    stripe_access_token = models.CharField('stripe_access_token', max_length=250, blank=True, null=True)
Estaría bien poner en la parte de stripe un editable=True para evitar que los admin puedan modificar este tipo de datos.

2020-04-05 12:37 UTC, angbongon commented on events/templates/event/list.html
> +            <button type="button" onclick="location.href='{% url 'attendee_payment' event.pk %}'" title="Cobrar">
Es posible que hagamos esta transacción en POST como se hace por ejemplo con "Ya no quiereo ir" (cancelar asistencia)? Puedes ver la view de esta funcionalidad para guiarte.

2020-04-05 12:37 UTC, angbongon commented on events/views.py
> +                        if transaction is not None:
Es una tontería pero ya que vas a cambiar cosas puedes también poner `if transaction` (comprueba si la variable está llena o es None, no te hace falta el is not None). Puedes aplicarlo en más lugares. No es necesario pero si quires puedes cambiarlo.

2020-04-05 18:25 UTC, angbongon submitted a review, later dismissed

2020-04-05 23:02 UTC, angelcalzadollamas requested changes
He creado un evento con un usuario y he intentado inscribirme con otro. Al inscribime me ha dado un error.

Los datos que he puesto en el form del javascript:
- email: angelcalzadollamas@gmail.com
- credit card: 4242 4242 4242 4242 
- fecha exp: 05/25
- secret number: 654

Aquí te dejo una imagen con el error que me ha salido

![Al inscribirme me pasa esto](https://user-images.githubusercontent.com/28622424/78512119-54d6ec00-77a2-11ea-887e-aca3ec531990.PNG)

2020-04-06 00:04 UTC, angbongon commented
> He creado un evento con un usuario y he intentado inscribirme con otro. Al inscribime me ha dado un error.
> 
> Los datos que he puesto en el form del javascript:
> - email: angelcalzadollamas@gmail.com
> - credit card: 4242 4242 4242 4242 
> - fecha exp: 05/25
> - secret number: 654
> 
> Aquí te dejo una imagen con el error que me ha salido
> 
> ![Al inscribirme me pasa esto](https://user-images.githubusercontent.com/28622424/78512119-54d6ec00-77a2-11ea-887e-aca3ec531990.PNG)
> 

No has hecho las migraciones

2020-04-07 08:48 UTC, angcallla commented
He probado y a mi me sigue cerrando la sesión de usuario. 

Por otro lado, deberíamos controlar que el botón del pago apareciera solo cuando el evento ha acabado, pero eso imagino que es de front. Confírmamelo.

2020-04-07 15:38 UTC, angelcalzadollamas submitted a review, later dismissed
Aprobado para probar si desplegado guarda la sesión del usuario.

2020-04-07 15:51 UTC, angbongon commented
Resuelve los conflictos @raunavcru y parece que sigues teniendo algo mal en las migraciones.

2020-04-07 16:37 UTC, angbongon approved these changes

2020-04-07 16:37 UTC, merged