CU-02 Buscar eventos localidad n CU-03 Buscar eventos con tú localización
eventshow/eventshow pull request #7
Opened 2020-03-23 10:10 UTC by santiborge97

In order to get some results, location filter will be automatically calculated with a range of 50 KM. This range can be changed with line 227 in views.py.

2020-03-23 15:42 UTC, angbongon requested changes
Tienes 7 _code smells_ mira SonarCloud y corrígelos.

2020-03-23 19:13 UTC, angbongon commented
Antes que nada debes resolver los conflictos @santiborge97

2020-03-23 19:14 UTC, angbongon approved these changes

2020-03-23 19:15 UTC, angbongon requested changes
Uno de lo cambios que claramente puedes hacer es usar una constante para la url de success

2020-03-23 20:28 UTC, angbongon commented
Parece que la build de Travis CI ha dado error porque estás intentando usar un archivo form que ya no se usa. Puede ser que al resolver los conflictos se te haya escapado algo. @santiborge97

2020-03-23 20:40 UTC, angbongon submitted a review, later dismissed

2020-03-23 20:43 UTC, angbongon commented
Te voy a pasar la mano con el tema de la complejidad cognitiva Don Santi, pero ten cuidaito.

2020-03-23 20:45 UTC, santiborge97 commented
Illo te juro que he intentado ponerlo de la forma mas simple y que sea más eficiente posible pero es que no hay manera, o por lo menos que yo sepa

2020-03-23 21:04 UTC, angbongon submitted a review, later dismissed
Todo correcto

2020-03-23 21:07 UTC, merged

2020-03-24 10:56 UTC, juanmiguelruiz commented
Fallo en el merge