CU-32 Anfitrión penalizado cancelación
eventshow/eventshow pull request #73
Opened 2020-04-07 20:44 UTC by raunavcru

Hay un problema en el botón de "Sí" ya que he tenido que cambiarlo con el de Stripe.
Le he puesto la misma clase e ID pero sale arriba en pequeño, no se muy bien por qué.

2020-04-08 11:41 UTC, angbongon submitted a review, later dismissed
Se aceptan los cambios y se pasa a QA

2020-04-08 11:42 UTC, angbongon commented
Voy a pedir una revisión a @juanmiguelruiz  también para que mire el tema del botón

2020-04-08 14:54 UTC, juanmiguelruiz commented
Botón arreglado

2020-04-08 17:04 UTC, angelcalzadollamas requested changes
Cosas que corregir:

1. La penalización se realiza si el evento se cancela 4 días **sin incluir el día de la celebración**. Por ejemplo: Si el evento es el 12 de abril, el 8 de abril ya me deberían estar penalizando

2. Cuando se cumple la condición de penalización el botón tarda un poco en aparecer. ¿Puede arreglarse? pregunta a @juanmiguelruiz 
![Sin título](https://user-images.githubusercontent.com/28622424/78812058-1c662680-79cb-11ea-8b11-8c6cb680394b.png)
![Captura](https://user-images.githubusercontent.com/28622424/78812061-1ff9ad80-79cb-11ea-8319-bb66dc2a5ce6.PNG)

3. La cantidad que el anfitrión debe pagar es la comisión que se hubiera llevado eventshow de cada entrada al evento, es decir, _la comisión de una entrada * número de asistentes al evento_.

En la siguiente imagen se ve que se le está cobrando al anfitrión 11,00€ que es el precio de una entrada de ese evento: 
![captura 3](https://user-images.githubusercontent.com/28622424/78812248-664f0c80-79cb-11ea-986a-be264133703a.PNG)

4. No veo que se guarde ninguna transacción en bbdd después de aceptar el pago. ¿Esto es porque lo haces directamente?

5. En el caso de que se deba penalizar al anfitrión, se le debería informar de alguna manera. Yo pondría en el mensaje de confirmación de eliminación: **Recibirá una penalización por ello (Más información en los términos y condiciones)**. Pregunta a @juanmiguelruiz

2020-04-08 17:30 UTC, angbongon requested changes
Sigue habiendo errores con las migraciones en Travis solucionalo

2020-04-09 14:35 UTC, angbongon submitted a review, later dismissed

2020-04-09 14:43 UTC, juanmiguelruiz submitted a review, later dismissed

2020-04-09 15:06 UTC, angelcalzadollamas requested changes
Corregido:
[x] De 3 a 4 días
No corregido:
1- Los botones a raíz del mensaje de penalización se mueven de sitio. Aquí te dejo una imagen de ello:
![Captura](https://user-images.githubusercontent.com/28622424/78909668-2c8e0c80-7a84-11ea-9127-b59a8da40e64.PNG)

2-Se le sigue cobrando el precio de una entrada al anfitrión, repito que es el **cálculo de una comisión de la entrada por el número de enrollments aceptados**. Aquí dejo primero una foto del precio del evento en bbdd y como es ese el precio que se le está cobrando:
![Captura3](https://user-images.githubusercontent.com/28622424/78909846-5f380500-7a84-11ea-8276-bf216f35bcf3.PNG)

![Captura2](https://user-images.githubusercontent.com/28622424/78909873-69f29a00-7a84-11ea-97af-9bc791e83ac3.PNG)

2020-04-09 17:12 UTC, angelcalzadollamas approved these changes
Todo correcto.

2020-04-09 17:14 UTC, merged