CU-03 Buscar eventos con tu localización y CU-04 Filtrar eventos - Refactorizado y correcciones
eventshow/eventshow pull request #80
Opened 2020-04-09 16:30 UTC by angbongon

Ahora es posible filtrar por categorías (CU-04) además de haberse corregido los errores pertienentes a la búsqueda por geolocalización.

2020-04-09 16:49 UTC, angbongon commented
@juanmiguelruiz te asigno como reviewer para que puedas mirar como se ve ahora el tema de los botones de categoría.

2020-04-09 16:55 UTC, juanmiguelruiz commented
Dejalo asi y lo cambiare yo

2020-04-09 16:55 UTC, juanmiguelruiz commented
acepta la pull

2020-04-09 16:55 UTC, juanmiguelruiz submitted a review, later dismissed

2020-04-09 16:56 UTC, angbongon commented
> acepta la pull

Espero a que acepte QA y hago el merge

2020-04-10 10:01 UTC, angelcalzadollamas requested changes
**Para corregir:**
Ahora cuando no activas la localización ya no sale el mensaje que puso santi de: No tienes activada la localización. Se debe avisar de ello, aquí una imagen de que no se ve:
![Ya no sale el mensaje de que no has activado la localización](https://user-images.githubusercontent.com/28622424/78982630-d7550800-7b22-11ea-95b3-072febfd0cd0.PNG)

**Proposición de mejora:**
Cuando filtras por una categoría, ¿Por qué se van los cuadros de las demás categorías? ¿No se podrían dejar pa poder ir cambiandolas facilmente? Aquí una imagen de como cuando filtras una categoría desaparecen las demás:
![No podrían seguir saliendo todas las categorías pa seguir cambiando de una a otra](https://user-images.githubusercontent.com/28622424/78982717-01a6c580-7b23-11ea-8b4f-9d1918f96e74.PNG)

2020-04-10 10:40 UTC, juanmiguelruiz commented
La verdad que este cambio se descartó por ser demasiado complicado por parte del back, ahora lo habeis hecho pero desde el front no estaba contemplado hacer esta vista en la planificacion ya que no solo hay que cambiarla en escritorio sino tambien en todo el responsive. Así que no hay ningun problema en hacerla pero cuando todo lo planificado este hecho.

2020-04-10 11:02 UTC, santiborge97 commented
Yo he hecho un commit con un apaño para mostrar el mensaje de error. Míralo a ver si te gusta @angbongon

2020-04-10 11:30 UTC, angcallla commented
Estoy de acuerdo con lo que dice juanmi, recuerdo que comentó que por la parte del front era complicado contemplar lo de las categorías. Sin embargo, lo del mensaje que debe aparecer si el usuario no tiene habilitada la ubicación debe aparecer. Mirare si está en dev y sino pediré que se ponga aunque sea a dev.

_Esta funcionalidad para a ser de prioridad baja, es decir, a la espera de que el front termine todas sus cosas y puda ponerse manos a la obra con esta tarea que se canceló en el sprint 2_

2020-04-11 14:44 UTC, juanmiguelruiz submitted a review, later dismissed

2020-04-11 16:23 UTC, angelcalzadollamas requested changes
Por qué si yo quiero poner una ubicación que no existe en el autocompletar me sale esto

![Captura](https://user-images.githubusercontent.com/28622424/79049053-85df7280-7c21-11ea-8e38-f9d573348100.PNG)

2020-04-11 16:28 UTC, angbongon commented
> Por qué si yo quiero poner una ubicación que no existe en el autocompletar me sale esto
> 
> ![Captura](https://user-images.githubusercontent.com/28622424/79049053-85df7280-7c21-11ea-8e38-f9d573348100.PNG)

Porque la suckas

2020-04-11 17:19 UTC, angelcalzadollamas approved these changes
Todo correcto. Le diré a juanmi que revise una cosa de front cuando esto esté en dev

2020-04-11 17:26 UTC, angbongon commented
> Todo correcto. Le diré a juanmi que revise una cosa de front cuando esto esté en dev

Calsadito calsadito... Ten cuidaito

2020-04-11 17:26 UTC, merged