CU-10 Gestionar eventos
eventshow/eventshow pull request #82
Opened 2020-04-09 21:11 UTC by raunavcru

Ya solo salen los errores de servidor y se ha deshabilitado la opción de modificar el precio, pero hay un problema, cuando hay un error y te devuelve la vista, se pierde el valor del precio. No da ningún error porque ya me ocupo de que se guarde, pero no se muestra.
También al poner todo en blanco, con los textos del los errores se alarga el formulario. No se si eso es un problema, pero para tenerlo en cuenta.

2020-04-10 10:53 UTC, juanmiguelruiz reviewed
La verdad es que no sabria solucionar eso, podria ser terreno del back o del front, no sabria decirlo.

2020-04-10 17:07 UTC, angbongon submitted a review, later dismissed

2020-04-10 17:46 UTC, raunavcru commented
He vuelto a dejar el update como estaba

2020-04-10 18:51 UTC, angelcalzadollamas requested changes
**Cosas que corregir:**


1. Si pongo el aforo a 0 el error que me sale es "Introduzca un aforo", siempre salía algo como "El aforo no puede ser 0". Imagen:
![Captura](https://user-images.githubusercontent.com/28622424/79014154-95e84b00-7b6a-11ea-8171-6252d50ce690.PNG)

2. Si pongo precio 0 el error que sale es "Introduzca un precio". Debería ser "El precio no puede ser 0". Imagen: 
![Captura](https://user-images.githubusercontent.com/28622424/79014292-e069c780-7b6a-11ea-9825-86bbaf4b1b06.PNG)

3. Lo mismo del apartado 1 y 2 pero con la edad. Imagen:
![Captura](https://user-images.githubusercontent.com/28622424/79014389-14dd8380-7b6b-11ea-96ef-ef915ce2c4e5.PNG)

4. En el número de la ubicación, el mensaje de error está en inglés. Imagen:
![Captura](https://user-images.githubusercontent.com/28622424/79014517-5b32e280-7b6b-11ea-9083-a9deb862faaf.PNG)

5. Si pongo letras en la hora, peta. Imágenes:
![Captura](https://user-images.githubusercontent.com/28622424/79014681-b1a02100-7b6b-11ea-8b82-cb324ffc0c27.PNG)
![Captura](https://user-images.githubusercontent.com/28622424/79014709-bfee3d00-7b6b-11ea-8ad4-f7bf6d1aad7a.PNG)

6. Si pongo de hora inicial 23:00 y hora final 1:00 me lo toma como que está empezando cuando acaba cuando las 1:00 se refiere al día siguiente (Esto es algo que ha encontrado manel y quisiera saber si se puede arreglar). Imagen:
![Captura](https://user-images.githubusercontent.com/28622424/79015005-4acf3780-7b6c-11ea-9c3d-c3308a2c8639.PNG)

2020-04-10 23:09 UTC, angelcalzadollamas approved these changes
Desde QA, todo correcto.

2020-04-11 01:40 UTC, angbongon approved these changes

2020-04-11 01:41 UTC, merged