CU-31 Asistente paga con bonificación
eventshow/eventshow pull request #83
Opened 2020-04-09 21:41 UTC by raunavcru

La parte de backend funciona, ahora, el JavaScript es un pop-up para meter la Credit Card y elegir si quieres el descuento, pero visualmente es horrible.

2020-04-10 10:49 UTC, juanmiguelruiz requested changes
No entiendo porque no se ha dejado la que te trae stripe por defecto, este cambio no esta contemplado en la planificación por parte del front y no se hará hasta que todo lo planificado este hecho.

Como solución propongo en vez de utilizar un estilo propio tal y como sale ahora, utilizar el checkout que te trae stripe por defecto de 2020 y en otra pestaña del navegador y cuando pagues vuelva a la pagina de eventshow(esto lo he visto en una pull req de front que he revisado)

como se ahora
<img width="923" alt="Captura de pantalla 2020-04-10 a las 12 43 16" src="https://user-images.githubusercontent.com/26764879/78985550-58170280-7b29-11ea-9225-33693cb63f8c.png">

propuesta de cambio escritorio
<img width="1552" alt="Captura de pantalla 2020-04-10 a las 12 48 03" src="https://user-images.githubusercontent.com/26764879/78985611-87c60a80-7b29-11ea-84bf-3b26b30d32db.png">

propuesta de cambio movil
<img width="1552" alt="Captura de pantalla 2020-04-10 a las 12 48 43" src="https://user-images.githubusercontent.com/26764879/78985650-9f9d8e80-7b29-11ea-8b5f-e23847e7fadc.png">

fuente: https://stripe.com/docs/payments/checkout

2020-04-10 12:17 UTC, angbongon commented
> No entiendo porque no se ha dejado la que te trae stripe por defecto, este cambio no esta contemplado en la planificación por parte del front y no se hará hasta que todo lo planificado este hecho.
> 
> Como solución propongo en vez de utilizar un estilo propio tal y como sale ahora, utilizar el checkout que te trae stripe por defecto de 2020 y en otra pestaña del navegador y cuando pagues vuelva a la pagina de eventshow(esto lo he visto en una pull req de front que he revisado)
> 
> como se ahora
> <img alt="Captura de pantalla 2020-04-10 a las 12 43 16" width="923" src="https://user-images.githubusercontent.com/26764879/78985550-58170280-7b29-11ea-9225-33693cb63f8c.png">
> 
> propuesta de cambio escritorio
> <img alt="Captura de pantalla 2020-04-10 a las 12 48 03" width="1552" src="https://user-images.githubusercontent.com/26764879/78985611-87c60a80-7b29-11ea-84bf-3b26b30d32db.png">
> 
> propuesta de cambio movil
> <img alt="Captura de pantalla 2020-04-10 a las 12 48 43" width="1552" src="https://user-images.githubusercontent.com/26764879/78985650-9f9d8e80-7b29-11ea-8b5f-e23847e7fadc.png">
> 
> fuente: https://stripe.com/docs/payments/checkout

En estoy estoy más o menos de acuerdo, ya se lo comenté a @raunavcru y @angbongon la cosa es que creo que también quiere cambiar el JS para poder poner un seleccionable que te deje pagar con descuento. El problema parace ser que ha tenido que cambiar el JS por completo para poder hacerlo, y no sé si usar el checkout de Stripe nuevo solucionará este problema.

2020-04-10 17:50 UTC, angcallla commented
Raúl avisame por slack para revisar esto cuando lo tengais

2020-04-10 23:52 UTC, angcallla commented
Aunque los coordinadores deben aceptar esto antes que yo, lo he visto y cuando accedo al detalle de un evento me sale este error:
![Captura](https://user-images.githubusercontent.com/28622424/79029972-23da2b00-7b97-11ea-85e8-1efbff4967c4.PNG)

2020-04-11 10:24 UTC, juanmiguelruiz requested changes
Cuando el usuario tiene 0 eventpoints sigue habiendo descuento

@angbongon @angcallla comprobarlo que a raul le va

2020-04-11 14:44 UTC, juanmiguelruiz submitted a review, later dismissed

2020-04-11 14:54 UTC, angbongon commented on events/views.py
> +            #services.EmailService().send_email(subject, body, [recipient])
@angcallla cuando revises descomenta esto. Imagino que está comentado por Raúl porque no tiene los credenciales.

2020-04-11 14:56 UTC, angbongon requested changes

2020-04-11 14:56 UTC, angbongon commented on events/templates/event/event_confirm_delete.html
> +                                data-amount="{% widthratio penalty 1 100|floatformat:'0' %}" data-locale="es" data-currency="eur"
El widthratio no hace falta si le pasa la cantidad correctamente desde el back

2020-04-11 14:57 UTC, juanmiguelruiz commented on events/templates/event/event_confirm_delete.html
> +                                data-amount="{% widthratio penalty 1 100|floatformat:'0' %}" data-locale="es" data-currency="eur"
Pues quitalo :)

2020-04-11 16:19 UTC, raunavcru commented on events/templates/event/event_confirm_delete.html
> +                                data-amount="{% widthratio penalty 1 100|floatformat:'0' %}" data-locale="es" data-currency="eur"
Si hace falta

2020-04-11 17:28 UTC, angbongon commented on events/templates/event/event_confirm_delete.html
> +                                data-amount="{% widthratio penalty 1 100|floatformat:'0' %}" data-locale="es" data-currency="eur"
Yo lo tengo cambiado en dev, tanto para eliminar cuenta como para este caso y da el precio bien.

2020-04-11 17:29 UTC, angbongon commented on events/templates/event/event_confirm_delete.html
> +                                data-amount="{% widthratio penalty 1 100|floatformat:'0' %}" data-locale="es" data-currency="eur"
Se puede ver en UserDeleteView y en el template correspondiente.

2020-04-11 18:10 UTC, angcallla commented on events/templates/event/event_confirm_delete.html
> +                                data-amount="{% widthratio penalty 1 100|floatformat:'0' %}" data-locale="es" data-currency="eur"
Puedo revisarlo ya????

2020-04-11 18:15 UTC, raunavcru commented on events/templates/event/event_confirm_delete.html
> +                                data-amount="{% widthratio penalty 1 100|floatformat:'0' %}" data-locale="es" data-currency="eur"
Por mi si

2020-04-11 18:20 UTC, angcallla commented on events/templates/event/event_confirm_delete.html
> +                                data-amount="{% widthratio penalty 1 100|floatformat:'0' %}" data-locale="es" data-currency="eur"
y por @angbongon

2020-04-11 19:54 UTC, angelcalzadollamas requested changes
No debería aparecer si quiera el modal si el usuario tiene 0 eventpoints:

![Captura](https://user-images.githubusercontent.com/28622424/79053599-ecbf5480-7c3e-11ea-9f54-390b436ff1fc.PNG)

2020-04-12 14:37 UTC, angbongon submitted a review, later dismissed
Los cambios por parte del back se aceptan.

2020-04-13 08:51 UTC, angelcalzadollamas requested changes
Correcciones front:

1- El modal no sale bien

2- No funcionan ninguno de los botones de este

![Modal bonificación](https://user-images.githubusercontent.com/28622424/79107438-a9670200-7d74-11ea-8c9e-f40d6cf00606.PNG)

2020-04-13 08:56 UTC, juanmiguelruiz commented
Puede ser cuando ya tiene registrada una tarjeta, prueba con usuario que nunca haya pagado. Después arreglaré ese caso

2020-04-13 17:47 UTC, angelcalzadollamas approved these changes
Todo correcto.

2020-04-13 17:49 UTC, merged