[fix] Transaction anterior
eventshow/eventshow pull request #93
Opened 2020-04-13 18:21 UTC by raunavcru

2020-04-14 10:21 UTC, angcallla commented
Un inciso con esto, he visto el último commit de esta pull y se tocan cosas de la vista detail event. Como dije ayer esta vista se ha cambiado y está en una pull por lo que podrían darse conflictos en una rama o en otra dependiendo del cuál mergee primero.

Solo para avisar y que no se piense que alguien a tocado algo.

2020-04-15 01:31 UTC, angelcalzadollamas requested changes
En este mensaje voy a mostrar las casuísticas que yo he probado para que veamos si me dejo algo atrás o no. Están marcados aquellos checbox de comprobaciones que van bien

**Comprobaciones**

[] 1.  Usuario se inscribe a evento con 0 eventpoints y sin tarjeta de crédito registrada.
    _La funcionalidad con respecto a las transacciones y eventpoints va pero el js de stripe no muestra el costo total de la entrada con la comision. Dejalo como estaba antes. Imagen de como se ve ahora:_
![1-El js de stripe no muestra el total a pagar](https://user-images.githubusercontent.com/28622424/79288805-fdcec680-7ec7-11ea-82f3-cb3c42e93e48.PNG)

[x] 2. Usuario se inscribe a evento sin eventpoints con tarjeta registrada.
[] 3. Usuario se inscribe a evento con eventpoints sin tarjeta registrada.
    _La funcionalidad con respecto a las transacciones y evenpoints van bien pero el css se ha roto. No le pongas en este caso a los botones el paréntesis mostrándo el precio ya que como luego sale el js de stripe, se va a acabar viendo. Aquí una imagen de como se ve ahora:_
![La disposición de los botones está mal](https://user-images.githubusercontent.com/28622424/79288950-6027c700-7ec8-11ea-9444-5e543d82f7d3.PNG)

[x] 4. Usuario se inscribe a evento con eventpoints y tarjeta registrada.
[x] 5. Anfitrión recibe pago de una transacción sin descuento.
[x] 6. Anfitrión recibe pago de una transacción con descuento.
[x] 7. Asistente cancela su asistencia con enrollment en estado pending a más de 3 días de la celebración.
[x] 8. Asistente cancela su asistencia con enrollment en estado pending a 3 días de la celebración.
[x] 9. Asistente cancela su asistencia con enrollment en estado accepted a más de 3 días de la celebración.
[x] 10. Asistente cancela su asistencia con enrollment en estado accepted a 3 días de la celebración.
[x] 11. Anfitrión cancela su evento a más de 4 días de la celebración.
[x] 12. Anfitrión cancela su evento a 4 días de la celebración.

> Me faltaría probar el olvido, pero como te dije, debes mergear dev a esta rama porque la tienes un poco antiguada dado que me ha dado un error que recuerdo se arregló en dev.

2020-04-15 20:16 UTC, angbongon commented
@angcallla en principio ya está implementado para cuando se elimina un usuario. Te recomiendo que a la hora de probarlo no uses el populate al completo, populalo sólo con usuarios, crea con cualquiera un evento y haz que unos pocos se inscriban (no todos para comprobar que se toque sólo a los que se deben tocar) y haz las pruebas. El tema de como se ve el modal cuando hace falta credit card no lo he tocado para que sea Juanmi el que lo modifique cuando suba la vista a dev.

2020-04-16 10:12 UTC, angelcalzadollamas requested changes
Ya te puedo enviar esto. No he podido revisar nada porque cuando un usuario tiene eventpoints, a la hora de inscribirse a un evento, no me da la opción de usarlos por lo que no puedo revisar lo referente a las transacciones y de más cosas.

Creo que llegados a este punto lo mejor será que me espere a que lo tengas todo listo junto a lo de juanmi para ya revisarlo todo en su totalidad

2020-04-16 11:40 UTC, angbongon commented
> Ya te puedo enviar esto. No he podido revisar nada porque cuando un usuario tiene eventpoints, a la hora de inscribirse a un evento, no me da la opción de usarlos por lo que no puedo revisar lo referente a las transacciones y de más cosas.
> 
> 
> 
> Creo que llegados a este punto lo mejor será que me espere a que lo tengas todo listo junto a lo de juanmi para ya revisarlo todo en su totalidad

Ya está arreglado. La variable que controlaba eso se había borrado.

2020-04-16 17:30 UTC, angelcalzadollamas requested changes
**Comprobaciones**

[x] 1.  Usuario se inscribe a evento con 0 eventpoints y sin tarjeta de crédito registrada.
[x] 2. Usuario se inscribe a evento sin eventpoints con tarjeta registrada.
[] 3. Usuario se inscribe a evento con eventpoints sin tarjeta registrada.
    _La funcionalidad con respecto a las transacciones y evenpoints van bien pero el css se ha roto. Lo primero la disposición de los botones ya no están bien y lo segundo en este caso en concreto lo que te señalo en amarillo no debería aparecer. Imagen:_
![caso 3](https://user-images.githubusercontent.com/28622424/79482967-dedc4b80-8011-11ea-80a3-04a1b2eb34b0.PNG)

[] 4. Usuario se inscribe a evento con eventpoints y tarjeta registrada.
   _La funcionalidad con respecto a las transacciones y los eventpoints están bien pero el css se ha roto. Lo que te marco en amarillo no debería estar. Imagen:_
![Caso 4](https://user-images.githubusercontent.com/28622424/79483785-0384f300-8013-11ea-8d81-8a82e86ad56d.PNG)

[x] 5. Anfitrión recibe pago de una transacción sin descuento.
[x] 6. Anfitrión recibe pago de una transacción con descuento.
[x] 7. Asistente cancela su asistencia con enrollment en estado pending a más de 3 días de la celebración.
[x] 8. Asistente cancela su asistencia con enrollment en estado pending a 3 días de la celebración.
[x] 9. Asistente cancela su asistencia con enrollment en estado accepted a más de 3 días de la celebración.
[x] 10. Asistente cancela su asistencia con enrollment en estado accepted a 3 días de la celebración.
[] 11. Anfitrión cancela su evento con enrollment de asistente a PENDING.
   _Me he inscrito a un evento, luego me he logueado como el anfitrión y lo he cancelado y al asistente no se les ha devuelto los eventpoints._
[x] 12. Anfitrión cancela su evento con enrollment a ACCEPTED.
[x] 13. Anfitrión rechaza enrollment.
[] 14. Anfitrión olvida sus datos.
    _No se olvidan los datos, sigo estando logueado como el usuario_

2020-04-16 22:07 UTC, merged