Botón de cobro
eventshow/eventshow pull request #98
Opened 2020-04-14 17:21 UTC by raunavcru

2020-04-14 20:02 UTC, angbongon submitted a review, later dismissed
Se aceptan los cambios y se pasa a QA

2020-04-14 21:42 UTC, angelcalzadollamas requested changes
**Correcciones:**
Cambiar mensaje de cobro "Ya se sido cobrado" a "Ya ha sido cobrado"

**Nueva comprobación:**
Me he dado cuenta de que si un evento termina y nadie se ha inscrito ni nada, cuando se termina al darle al botón de cobrar te devuelve a la vista de mis experiencias sin anfitrión sin especificar nada.

_Hacer que si un evento no tiene enrollments aceptados cuando este termina, ponga en lugar del botón de cobrar: "No hay nada que cobrar"_

2020-04-14 21:49 UTC, juanmiguelruiz commented
Estoy de acuerdo con el bouss pero el copywritting deja mucho que desear jajajaj

Yo pondría

Cuando se ha realizado el cobro: Evento cobrado.
Si no hay huéspedes: Evento sin huéspedes.

2020-04-14 22:09 UTC, raunavcru commented
Es una vista, no se como acceder a cada evento

2020-04-15 17:34 UTC, angbongon commented
Eso que proponéis, a nivel de back no es tan fácil. Debido a que la vista es una lista de eventos y dentro de una template no se pueden hacer queries a la BBDD

2020-04-15 18:00 UTC, angbongon commented
La solución que he aplicado no es muy eficiente pero es lo que hay con el tiempo del que disponemos.

2020-04-15 20:56 UTC, angelcalzadollamas approved these changes
Todo correcto.

2020-04-15 20:57 UTC, angcallla commented
Elimino a juanmi porque no suele mirar estas pull request y lo que es el css se ve bien.

2020-04-15 21:06 UTC, merged